// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izsnzkofmlcrwbmxhvkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6c256a29mbWxjcndibXhodmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA4MDYyOTQsImV4cCI6MjA3NjM4MjI5NH0.6PZj45_wVryMQO6LPi9HUme1GKt6U_XjeS-_EKPQp4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});